### ISSUE TITLE
list dependencies as packages of major distros

### ISSUE THREAD

**Issue by demon36** [NotixApp/Notix#28]
how about list debian packages that should be installed to run the app image ?

**Comment by lordadamson** [comment]
I'm using app image to avoid using apt :smile: 
I wanna avoid distro specific stuff. Also I'll have to make a 3rd party repository and stuff.

**Comment by lordadamson** [comment]
I wouldn't mind if if someone put it in a .deb though :smile:

**Comment by demon36** [comment]
why make 3rd party repo, packaging in a deb is not what i meant
I meant listing the packages that contain needed .so files in the readme

**Comment by lordadamson** [comment]
oh I misunderstood :smile: well the appimage should not need any external dependencies.

**Comment by lordadamson** [comment]
having issues running it?

**Comment by demon36** [comment]
yes

**Comment by lordadamson** [comment]
run it in terminal and copy/paste the output here... or maybe on a new issue.

**Comment by demon36** [comment]
$ QT_DEBUG_PLUGINS=1 ./Notix-x86_64.AppImage
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_Notix-5JEZRt/usr/bin/platforms" ...
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted (core dumped)

**Comment by lordadamson** [comment]
are you sure you have the latest release I just uploaded a few minutes ago? :smile:

**Comment by lordadamson** [comment]
if so, what distro are you using?

**Comment by demon36** [comment]
should i close this ?

**Comment by lordadamson** [comment]
yup :smile:
