### ISSUE TITLE
Adding a better description to "How to contribute?" section.

### ISSUE THREAD

**Issue by AbdAllahBoda** [NotixApp/Notix#33]
A newbie would have to know that he should fork the repo, commit his changes to his fork, then send a pull requset.

**Comment by lordadamson** [comment]
hmmmmmmmmmmmmmmmm :smile: maybe direct newbies to [iusegit](https://github.com/Open-Source-Community/iusegit)?

**Comment by AbdAllahBoda** [comment]
Nice idea, I don't know that this exists! :D

Nonetheless, All Open source repos I've seen before had these simple instructions in its [How to contruibete] section. :)
