### ISSUE TITLE
Compile on windows and make sure it works as expected

### ISSUE THREAD

**Issue by lordadamson** [NotixApp/Notix#7]

**Comment by AbdAllahBoda** [comment]
I can take this issue if you provided a "How to use" section. :)

**Comment by lordadamson** [comment]
cool :smile: take a look at the [readme.md](https://github.com/NotixApp/Notix/blob/master/README.md) file.

**Comment by lordadamson** [comment]
let me know if you're working on it so that I'd place an in progress label on it.

**Comment by AbdAllahBoda** [comment]
I've seen the update, the free version of Qt5 will be enough I guess, right?
* just making sure *

**Comment by AbdAllahBoda** [comment]
If so, I'll let you know once I set up the environment locally.

**Comment by lordadamson** [comment]
Sure will. Choose the open source one.

On Mar 18, 2018 11:52 PM, AbdAllah Abd El-fatah <notifications@github.com> wrote:

I've seen the update, the free version of Qt5 will be enough I guess, right?

  *   just making sure *

**Comment by AbdAllahBoda** [comment]
Dude!, It tells me that I need nearly 40 GiB to install!, Am I doing something wrong?

This is A HUGE space!

**Comment by lordadamson** [comment]
You're probably trying to install every Qt version there is in the world :smile: 
Only check the latest version. (Currently that's qt 5.10.1)
And you don't even need every single package within.
You only need the first one: `desktop <compiler> 64 bit`.

Let me know how that goes.

**Comment by AbdAllahBoda** [comment]
I was trying to install all packages within Qt 5.10.1 actually. :D 

My first entry is MSVC 2013 64-bit. I guess that's the one, right?

**Comment by lordadamson** [comment]
yes it is :smile: 
and make sure you install the tools (Qtcreator).

**Comment by AbdAllahBoda** [comment]
Tested and working.

Please close this issue.

**Comment by lordadamson** [comment]
Thank you! :heart:
